server:
  port: 8082
spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/venta
    username: root
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/